from enum import Enum

__all__ = ['LanguageCode']


class LanguageCode(str, Enum):
    arb = 'arb'
    cmn_cn = 'cmn-CN'
    cy_gb = 'cy-GB'
    da_dk = 'da-DK'
    de_de = 'de-DE'
    en_au = 'en-AU'
    en_gb = 'en-GB'
    en_gb_wls = 'en-GB-WLS'
    en_in = 'en-IN'
    en_us = 'en-US'
    es_es = 'es-ES'
    es_mx = 'es-MX'
    es_us = 'es-US'
    fr_ca = 'fr-CA'
    fr_fr = 'fr-FR'
    is_is = 'is-IS'
    it_it = 'it-IT'
    ja_jp = 'ja-JP'
    hi_in = 'hi-IN'
    ko_kr = 'ko-KR'
    nb_no = 'nb-NO'
    nl_nl = 'nl-NL'
    pl_pl = 'pl-PL'
    pt_br = 'pt-BR'
    pt_pt = 'pt-PT'
    ro_ro = 'ro-RO'
    ru_ru = 'ru-RU'
    sv_se = 'sv-SE'
    tr_tr = 'tr-TR'
